F-Log/backend

src/main/java/com/f_log/flog/domain/Gender.java, src/main/java/com/f_log/flog/domain/Member.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#2 -> origin
=> Feat/#2 Member 엔티티 구현

src/main/java/com/f_log/flog/domain/Food.java
[v] 기능 추가
[] 기능 삭제
[] 버그 수정
[] 의존성, 환경 변수, 빌드 관련 코드 업데이트
ex) feat/#6 -> main
없음
=> feat: Food entity

src/main/java/com/f_log/flog/domain/Member.java, src/main/java/com/f_log/flog/global/config/JpaAuditingConfiguration.java, src/main/java/com/f_log/flog/global/domain/BaseEntity.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#5 -> main
=> feat: BaseEntity 추가

src/main/java/com/f_log/flog/domain/Inbody.java, src/main/java/com/f_log/flog/domain/Member.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#10 -> main
=> feat: Inbody 엔티티 추가

src/main/java/com/f_log/flog/domain/Diet.java, src/main/java/com/f_log/flog/domain/Food.java, src/main/java/com/f_log/flog/domain/MealType.java
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#8 -> main
Food 클래스에 Diet와 연관관계 설정
=> feat: add Diet entity

src/main/java/com/f_log/flog/domain/Inbody.java, src/main/java/com/f_log/flog/domain/InbodyFeedback.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#12 -> main
=> feat: inbodyfeedback 엔티티 추가

src/main/java/com/f_log/flog/domain/Diet.java, src/main/java/com/f_log/flog/domain/DietFeedback.java, src/main/java/com/f_log/flog/domain/Food.java
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#14 -> main
- Diet 클래스 연관관계 설정
- Food extends BaseEntity
=> feat: DietFeedback entity 

src/main/java/com/f_log/flog/domain/DailyActivity.java, src/main/java/com/f_log/flog/domain/FoodPreference.java, src/main/java/com/f_log/flog/domain/HealthInformation.java, src/main/java/com/f_log/flog/domain/Inbody.java, src/main/java/com/f_log/flog/domain/InbodyFeedback.java, src/main/java/com/f_log/flog/domain/Member.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#17 -> main
=> Feat/#17 healthinformation 엔티티 추가, inbody 연관관계 로딩 방식 수정

src/main/java/com/f_log/flog/domain/Allergy.java, src/main/java/com/f_log/flog/domain/Member.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#20 -> main
=> feat: Allergy 엔티티 추가, 연관관계 매핑

src/main/java/com/f_log/flog/domain/Exercise.java, src/main/java/com/f_log/flog/domain/ExerciseIntensity.java, src/main/java/com/f_log/flog/domain/ExercisePurpose.java, src/main/java/com/f_log/flog/domain/Member.java
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#18 -> main
- Member와의 1:1 연관관계
=> feat: add Exercise entity 

src/main/java/com/f_log/flog/domain/DietFeedback.java
-[] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
ex) fix/#24 -> main
change Inbody to Diet
=> fix: change Inbody to Diet

src/main/java/com/f_log/flog/domain/Diet.java, src/main/java/com/f_log/flog/domain/Member.java
-[] 기능 추가
-[] 기능 삭제
-[✅] 버그 수정
ex) fix/#26 -> main
=> fix: Diet 엔티티 중복되는 칼럼, Member 엔티티 mappedBy 수정

src/main/java/com/f_log/flog/healthinformation/controller/HealthInformationController.java, src/main/java/com/f_log/flog/healthinformation/domain/DailyActivity.java, src/main/java/com/f_log/flog/healthinformation/domain/HealthInformation.java, src/main/java/com/f_log/flog/healthinformation/repository/HealthInformationRepository.java, src/main/java/com/f_log/flog/healthinformation/service/HealthInformationService.java, src/main/java/com/f_log/flog/member/domain/Member.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#34 -> main
healthinformation 엔티티에 memberuuid 필드 추가
=> feat: HealthInformation crud api 구현

build.gradle, src/main/resources/application.yml
-[x] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[x] 의존성, 환경 변수, 빌드 관련 코드 업데이트
ex) feat/#36 -> main
- tomcat port 80 -> 8080으로 변경
- swagger at http://localhost:8080/swagger-ui/index.html#/
=> feat: swagger

src/main/java/com/f_log/flog/healthinformation/controller/HealthInformationController.java, src/main/java/com/f_log/flog/healthinformation/dto/HealthInformationMapper.java, src/main/java/com/f_log/flog/healthinformation/dto/HealthInformationRequestDto.java, src/main/java/com/f_log/flog/healthinformation/dto/HealthInformationResponseDto.java, src/main/java/com/f_log/flog/healthinformation/service/HealthInformationService.java
-[✅] 기능 추가
-[✅] 리팩토링
-[] 기능 삭제
-[] 버그 수정
ex) chore/#40 -> main
health-info dto, mapper, 주석 추가
=> chore: health-info dto, mapper, 주석 추가

src/main/java/com/f_log/flog/domain/InbodyFeedback.java, src/main/java/com/f_log/flog/global/domain/BaseEntity.java, src/main/java/com/f_log/flog/inbody/controller/InbodyController.java, src/main/java/com/f_log/flog/inbody/domain/Inbody.java, src/main/java/com/f_log/flog/inbody/dto/InbodyMapper.java, src/main/java/com/f_log/flog/inbody/dto/InbodyRequestDto.java, src/main/java/com/f_log/flog/inbody/dto/InbodyResponseDto.java, src/main/java/com/f_log/flog/inbody/repository/InbodyRepository.java, src/main/java/com/f_log/flog/inbody/service/InbodyService.java, src/main/java/com/f_log/flog/inbodyfeedback/controller/InbodyFeedbackController.java, src/main/java/com/f_log/flog/inbodyfeedback/domain/InbodyFeedback.java, src/main/java/com/f_log/flog/inbodyfeedback/dto/InbodyFeedbackMapper.java, src/main/java/com/f_log/flog/inbodyfeedback/dto/InbodyFeedbackRequestDto.java, src/main/java/com/f_log/flog/inbodyfeedback/dto/InbodyFeedbackResponseDto.java, src/main/java/com/f_log/flog/inbodyfeedback/repository/InbodyFeedbackRepository.java, src/main/java/com/f_log/flog/inbodyfeedback/service/InbodyFeedbackService.java, src/main/java/com/f_log/flog/member/domain/Member.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#43 -> main
feat: inbody crud api 구현
fix: Inbody POST URL에서 memberUuid 삭제
fix: 생성날짜, 수정날짜 표시 안되는 것 수정, 인바디 생성날짜, 수정날짜 표시되도록 수정
feat: inbody-feedback crud api 구현
=> feat: inbody+inbody_feedback crud api 구현

src/main/java/com/f_log/flog/diet/domain/Diet.java, src/main/java/com/f_log/flog/dietfeedback/controller/DietFeedbackController.java, src/main/java/com/f_log/flog/dietfeedback/domain/DietFeedback.java, src/main/java/com/f_log/flog/dietfeedback/dto/DietFeedbackDto.java, src/main/java/com/f_log/flog/dietfeedback/dto/DietFeedbackMapper.java, src/main/java/com/f_log/flog/dietfeedback/dto/DietFeedbackRequest.java, src/main/java/com/f_log/flog/dietfeedback/repository/DietFeedbackRepository.java, src/main/java/com/f_log/flog/dietfeedback/service/DietFeedbackService.java
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#45 -> main
=> feat: DietFeedback CRUD api v1 구현

build.gradle, src/main/java/com/f_log/flog/allergy/domain/Allergy.java, src/main/java/com/f_log/flog/diet/domain/Diet.java, src/main/java/com/f_log/flog/dietfeedback/domain/DietFeedback.java, src/main/java/com/f_log/flog/exercise/domain/Exercise.java, src/main/java/com/f_log/flog/food/domain/Food.java, src/main/java/com/f_log/flog/healthinformation/domain/HealthInformation.java, src/main/java/com/f_log/flog/inbodyfeedback/domain/InbodyFeedback.java, src/main/java/com/f_log/flog/member/domain/Member.java, src/main/resources/application.yml
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#49 -> main
- mysql 연동
- ID generation type 변동
=> feat: mysql 연동

src/main/java/com/f_log/flog/food/domain/Food.java, src/main/java/com/f_log/flog/food/dto/FoodRequestDto.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) fix/#52 -> main
=> feat: memberUuid 필드 추가

build.gradle, src/main/java/com/f_log/flog/diet/controller/DietController.java, src/main/java/com/f_log/flog/diet/domain/Diet.java, src/main/java/com/f_log/flog/diet/dto/CreateDietRequest.java, src/main/java/com/f_log/flog/diet/dto/DietDto.java, src/main/java/com/f_log/flog/diet/dto/UpdateDietRequest.java, src/main/java/com/f_log/flog/dietfeedback/controller/DietFeedbackController.java, src/main/java/com/f_log/flog/dietfeedback/domain/DietFeedback.java, src/main/java/com/f_log/flog/dietfeedback/dto/DietFeedbackRequest.java, src/main/java/com/f_log/flog/dietfeedback/service/DietFeedbackService.java, src/main/java/com/f_log/flog/global/config/RestTemplateConfig.java, src/main/java/com/f_log/flog/gpt/GptController.java, src/main/java/com/f_log/flog/gpt/GptService.java, src/main/java/com/f_log/flog/inbody/controller/InbodyController.java, src/main/java/com/f_log/flog/inbody/repository/InbodyRepository.java, src/main/java/com/f_log/flog/inbody/service/InbodyService.java
-[v] 기능 추가
ex) feat/#55 -> main
- GptController로의 요청을 통해 DietFeedback 생성
=> feat: Diet feedback을 위한 Flask 서버와의 데이터 통신

src/main/java/com/f_log/flog/diet/domain/Diet.java, src/main/java/com/f_log/flog/diet/dto/CreateDietRequest.java, src/main/java/com/f_log/flog/diet/dto/DietDto.java, src/main/java/com/f_log/flog/diet/dto/DietMapper.java, src/main/java/com/f_log/flog/diet/dto/UpdateDietRequest.java, src/main/java/com/f_log/flog/diet/service/DietService.java, src/main/java/com/f_log/flog/dietfeedback/controller/DietFeedbackController.java, src/main/java/com/f_log/flog/food/domain/Food.java, src/main/java/com/f_log/flog/food/dto/FoodDto.java, src/main/java/com/f_log/flog/food/dto/FoodMapper.java, src/main/java/com/f_log/flog/food/dto/FoodRequestDto.java, src/main/java/com/f_log/flog/food/service/FoodService.java, src/main/java/com/f_log/flog/gpt/GptController.java, src/main/java/com/f_log/flog/gpt/GptService.java, src/main/java/com/f_log/flog/inbodyfeedback/controller/InbodyFeedbackController.java, src/main/java/com/f_log/flog/inbodyfeedback/domain/InbodyFeedback.java, src/main/java/com/f_log/flog/inbodyfeedback/dto/InbodyFeedbackRequestDto.java, src/main/java/com/f_log/flog/inbodyfeedback/service/InbodyFeedbackService.java
-[v] 기능 추가
ex) feat/#59 -> main
- Diet, Food 필드에 Sugar, Calories 추가
- InbodyFeedback을 위한 api endpoint 생성
=> feat: Flask 서버와 통신 후 InbodyFeedback 생성 및 Sugar, Calories 필드 추가

src/main/java/com/f_log/flog/diet/domain/Diet.java, src/main/java/com/f_log/flog/diet/repository/DietRepository.java, src/main/java/com/f_log/flog/diet/service/DietService.java, src/main/java/com/f_log/flog/dietfeedback/controller/DietFeedbackController.java, src/main/java/com/f_log/flog/dietfeedback/domain/DietFeedback.java, src/main/java/com/f_log/flog/dietfeedback/dto/DietFeedbackDto.java, src/main/java/com/f_log/flog/dietfeedback/dto/DietFeedbackMapper.java, src/main/java/com/f_log/flog/dietfeedback/repository/DietFeedbackRepository.java, src/main/java/com/f_log/flog/dietfeedback/service/DietFeedbackService.java, src/main/java/com/f_log/flog/dietfood/controller/DietFoodController.java, src/main/java/com/f_log/flog/dietfood/domain/DietFood.java, src/main/java/com/f_log/flog/dietfood/dto/DietFoodRequestDTO.java, src/main/java/com/f_log/flog/dietfood/dto/DietFoodResponseDTO.java, src/main/java/com/f_log/flog/dietfood/repository/DietFoodRepository.java, src/main/java/com/f_log/flog/dietfood/service/DietFoodService.java, src/main/java/com/f_log/flog/food/controller/FoodController.java, src/main/java/com/f_log/flog/food/domain/Food.java, src/main/java/com/f_log/flog/food/dto/FoodDto.java, src/main/java/com/f_log/flog/food/dto/FoodMapper.java, src/main/java/com/f_log/flog/food/repository/FoodRepository.java, src/main/java/com/f_log/flog/food/service/FoodService.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#67 -> main
chore: diet,food,dietfood,dietfeedback ID생성 전략을 UUID로 변경
=> chore: diet,food,dietfood,dietfeedback ID생성 전략을 UUID로 변경

src/main/java/com/f_log/flog/allergy/controller/AllergyController.java, src/main/java/com/f_log/flog/allergy/domain/Allergy.java, src/main/java/com/f_log/flog/allergy/dto/AllergyDto.java, src/main/java/com/f_log/flog/allergy/dto/AllergyMapper.java, src/main/java/com/f_log/flog/allergy/repository/AllergyRepository.java, src/main/java/com/f_log/flog/allergy/service/AllergyService.java, src/main/java/com/f_log/flog/diet/domain/Diet.java, src/main/java/com/f_log/flog/exercise/domain/Exercise.java, src/main/java/com/f_log/flog/exercise/repository/ExerciseRepository.java, src/main/java/com/f_log/flog/exercise/service/ExerciseService.java, src/main/java/com/f_log/flog/healthinformation/controller/HealthInformationController.java, src/main/java/com/f_log/flog/healthinformation/domain/HealthInformation.java, src/main/java/com/f_log/flog/healthinformation/repository/HealthInformationRepository.java, src/main/java/com/f_log/flog/healthinformation/service/HealthInformationService.java, src/main/java/com/f_log/flog/inbody/domain/Inbody.java, src/main/java/com/f_log/flog/inbodyfeedback/controller/InbodyFeedbackController.java, src/main/java/com/f_log/flog/inbodyfeedback/domain/InbodyFeedback.java, src/main/java/com/f_log/flog/inbodyfeedback/dto/InbodyFeedbackMapper.java, src/main/java/com/f_log/flog/inbodyfeedback/dto/InbodyFeedbackResponseDto.java, src/main/java/com/f_log/flog/inbodyfeedback/repository/InbodyFeedbackRepository.java, src/main/java/com/f_log/flog/inbodyfeedback/service/InbodyFeedbackService.java, src/main/java/com/f_log/flog/member/controller/MemberController.java, src/main/java/com/f_log/flog/member/domain/Member.java, src/main/java/com/f_log/flog/member/dto/MemberMapper.java, src/main/java/com/f_log/flog/member/service/MemberService.java
-[x] 기능 추가
ex) feat/#66 -> main
- Allergy ID 생성 방식을 UUID로 변경
- Exercise ID 생성 방식을 UUID로 변경
- HealthInformation ID 생성 방식을 UUID로 변경
- InbodyFeedback ID 생성 방식을 UUID로 변경
- Member ID 생성 방식을 UUID로 변경
=> feat: Allergy, Exercise, HealthInformation, InbodyFeedback, Member 생성 id를 UUID 방식으로 변경

src/main/java/com/f_log/flog/inbody/domain/Inbody.java, src/main/java/com/f_log/flog/inbody/dto/InbodyMapper.java, src/main/java/com/f_log/flog/inbody/dto/InbodyRequestDto.java, src/main/java/com/f_log/flog/inbody/dto/InbodyResponseDto.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) chore/#71 -> main
inbody 엔티티에 fatFreeMass(제지방량) 필드 추가
=> chore: inbody 엔티티에 fatFreeMass(제지방량) 필드 추가

src/main/java/com/f_log/flog/exercise/domain/Exercise.java, src/main/java/com/f_log/flog/exercise/dto/ExerciseMapper.java, src/main/java/com/f_log/flog/exercise/dto/ExerciseResponseDto.java, src/main/java/com/f_log/flog/exercise/service/ExerciseService.java, src/main/java/com/f_log/flog/healthinformation/domain/HealthInformation.java, src/main/java/com/f_log/flog/healthinformation/dto/HealthInformationRequestDto.java, src/main/java/com/f_log/flog/healthinformation/dto/HealthInformationResponseDto.java, src/main/java/com/f_log/flog/healthinformation/service/HealthInformationService.java, src/main/java/com/f_log/flog/inbody/domain/Inbody.java, src/main/java/com/f_log/flog/inbody/dto/InbodyMapper.java, src/main/java/com/f_log/flog/member/domain/Member.java
✅ 버그 수정
ex) fix/#73 ->main
- Exercise, HealthInformation, Inbody에 각각 존재하던 memberUuid 필드를 제거함
=> fix: Exercise, HealthInformation, Inbody에 각각 memberUuid 필드 제거

src/main/java/com/f_log/flog/global/config/CorsConfig.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#75 -> main
=> feat: 프론트엔드 연동

src/main/java/com/f_log/flog/member/controller/MemberController.java, src/main/java/com/f_log/flog/member/domain/Member.java, src/main/java/com/f_log/flog/member/dto/MemberLoginResponseDto.java, src/main/java/com/f_log/flog/member/repository/MemberRepository.java, src/main/java/com/f_log/flog/member/service/MemberService.java, src/main/java/com/f_log/flog/member/util/PasswordUtils.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#78-> main
=> feat: 세션 로그인 구현

src/main/java/com/f_log/flog/diet/controller/DietController.java, src/main/java/com/f_log/flog/diet/dto/DietDetailDto.java, src/main/java/com/f_log/flog/diet/repository/DietRepository.java, src/main/java/com/f_log/flog/diet/service/DietService.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#82-> main
mealdate, memberUuid로 식단 조회
=> feat: mealdate, memberUuid로 mealType에 따른 식단 조회

src/main/java/com/f_log/flog/allergy/controller/AllergyController.java, src/main/java/com/f_log/flog/allergy/repository/AllergyRepository.java, src/main/java/com/f_log/flog/allergy/service/AllergyService.java
-[✅] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/#88 -> main
=> feat: member allergy 정보 최근 순으로 조회 api 구현
